trigger:
- main
pr: none  # Disable PR triggers, can be adjusted as needed
pool:
  vmImage: 'ubuntu-latest'
steps:
- script: |
    # Install Ansible
    pip3 install "ansible==2.9.17"
  displayName: 'Install Ansible'
  
- script: |
    # Install Ansible rm module
    pip3 install ansible[azure]
  displayName: 'Install Ansible rm module'
  
- script: |
    # Run Ansible playbook to create Azure App Service
    ansible-playbook create-linux-app-svc.yml
  displayName: 'Run Ansible Playbook'
  env:
    AZURE_SUBSCRIPTION_ID: $(AZURE_SUBSCRIPTION_ID)
    AZURE_CLIENT_ID: $(AZURE_CLIENT_ID)
    AZURE_SECRET: $(AZURE_SECRET) 
    AZURE_TENANT: $(AZURE_TENANT) 